"""clave unica en tmdb_id para impedir duplicados

Revision ID: 79e765245114
Revises: c2c79c356dd1
Create Date: 2026-09-03 19:32:34.388636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e765245114'
down_revision: Union[str, Sequence[str], None] = 'c2c79c356dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_watched_tmdb_id', 'watched_movies', ['tmdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watched_tmdb_id', 'watched_movies', type_='unique')
    # ### end Alembic commands ###
