"""crear watched_movies

Revision ID: c2c79c356dd1
Revises: 
Create Date: 2026-08-30 12:27:05.938598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c79c356dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_movies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_movies_tmdb_id'), 'watched_movies', ['tmdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_movies_tmdb_id'), table_name='watched_movies')
    op.drop_table('watched_movies')
    # ### end Alembic commands ###
